### ISSUE TITLE
PracticeMode Needs Refactoring

### ISSUE THREAD

**Issue by Zackazt** [Zackazt/CompTIA-Aplus-Study-and-Practice#1]
Currently the PracticeMode activity is very inefficient and messy as it was something I threw together quickly.  We should start by refactoring PracticeMode.java to be easier to expand upon.

**Comment by ZacharyDavidSaunders** [comment]
I agree... I will open a new branch on the repository and we can push our commits to that branch, then merge it back to master when it is complete. This allows us to have several work-in-progress changes at a time. 

I have marked this issue as an "enhancement". As we create more and more issues, it may be helpful to categorize them.

**Comment by ZacharyDavidSaunders** [comment]
Commit: https://github.com/Zackazt/CompTIA-Aplus-Study-and-Practice/commit/a1070c07b51ac5c29753dd7dd8b95e0e5a67b857
