### ISSUE TITLE
App Crashes After User Exits & Re-enters Sections

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [Zackazt/CompTIA-Aplus-Study-and-Practice#7]
**Observed Problem / Data:** 
When the steps to reproduce are followed, the app crashes. I first observed this problem on version 1.4 using a HTC One M8 with the Android Version 6.0, software version 6.21.605.3.

<img src="https://cloud.githubusercontent.com/assets/14244868/18415602/17d299ce-77ad-11e6-96e6-4be2f9525335.png" height = "380" width="275" >

**Expected:**
The app should not crash.

**Steps To Reproduce:**
* Open the app
* Open the "902" section
* Open the "Windows Features" section
* Click the "back" navigation button (the native Android button, not the button in the app)
* Open the "Command Line Tools" section
* Click the "back" navigation button (the native Android button, not the button in the app)
* Open the "Windows Features" section
* Observe the crash

**Comment by ZacharyDavidSaunders** [comment]
Issue #7 branch created.

**Comment by ZacharyDavidSaunders** [comment]
@Zackazt,
Can you please look into this? I would do it myself, but I am still struggling with my SDKs.

**Comment by Zackazt** [comment]
I'm unable to replicate the issue on my Moto G4 running Android 6.0, but I did find an issue with the Windows Features Activity.  I believe the issue has been repaired, I will update it in the Play store and I have pushed the updated code to the Issue-#7 branch.  Please grab the update and try it again to let me know if the issue continues.  What version of Android are you on?

**Comment by Zackazt** [comment]
I was able to replicate the issue. Looking into it now, I'll come back with a fix.

**Comment by Zackazt** [comment]
Repaired.

**Comment by ZacharyDavidSaunders** [comment]
Pull Request :#8 
Merged and closed
